# Generated by Django 4.2.1 on 2023-06-20 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='discount_price',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
