# Generated by Django 4.2.1 on 2023-06-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo_url',
            field=models.ImageField(upload_to='images'),
        ),
    ]
