# Generated by Django 4.2.1 on 2023-06-20 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_discount_price_alter_menu_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
